### ISSUE TITLE
Icon contribution Guide 

### ISSUE THREAD

**Issue by gurjarshakti** [trenta-io/trenta-icons#35]
Hello Guys !! 
Can we build a contribution so someone can resolve the old issue we have in this repo? 
Thank you

**Comment by KevDoy** [comment]
Hey @gurjarshakti! It's a work in progress. We started one here: https://trenta.io/brand.html

**Comment by gurjarshakti** [comment]
ok Thanks @KevDoy. Also where I can find the requested icon by users?

**Comment by KevDoy** [comment]
Right now we're just keeping the Issues open for that. We previously had a running list on Google Sheets, then Trello - but we've decided to wipe the slate clean after a huge icon push. Now that things have slowed a bit we're just going to stick to issues open on this GitHub repo. Makes contribution much easier plus it allows better discussion.

**Comment by KevDoy** [comment]
@KennyStier61  @gurjarshakti You should see a larger list in issues later today
