### ISSUE TITLE
Battery Icons

### ISSUE THREAD

**Issue by KennyStier61** [trenta-io/trenta-icons#37]
Gnome has changed its battery naming scheme, having icons for each 10% of charge for both charging and discharging states

Here are the Gnome defaults
![Screenshot from 2019-10-23 23-25-52](https://user-images.githubusercontent.com/4749568/67450862-bccab900-f5ec-11e9-9318-05009c86394b.png)

**Comment by KennyStier61** [comment]
More info https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/1908

**Comment by KevDoy** [comment]
On it.

**Comment by KevDoy** [comment]
@KennyStier61 ready to be tested with pull request #69

**Comment by KevDoy** [comment]
Merged 30ed526b9b1ca019cde8099eb387be4196312edb
Pending testing.
