### ISSUE TITLE
Move to Vector

### ISSUE THREAD

**Issue by KennyStier61** [trenta-io/trenta-icons#6]
Raster images are great!

But they're ginormous. The latest release is 57 MB, compared to Numix's much larger collection requiring only 1.1 MB.

And they don't blend well.
![screenshot from 2017-12-04 22-28-25](https://user-images.githubusercontent.com/4749568/33588810-d8d06014-d942-11e7-9e07-6f8e11aea74b.png)
(look very closely between the power and night light icons)

When combined with other themes, the rasters do not change to the color directed by the theme. Instead the stubborn icons become hard or nearly impossible to see.

**Comment by KevDoy** [comment]
Making great progress.
Status icons have been converted and updated though they still require further testing. 

Applications are are over 50% complete
