### ISSUE TITLE
install trenta-icons not working

### ISSUE THREAD

**Issue by mali917** [trenta-io/trenta-icons#70]
[admin1@admin1 Downloads]$ cd rainier-ui-icons-git/
[admin1@admin1 rainier-ui-icons-git]$ makepkg -Acs
==> Making package: rainier-ui-icons-git 0.r446.9460016-1 (Sun 23 Feb 2020 02:38:58)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating rainier-ui-icons git repo...
Fetching origin
==> Validating source files with sha256sums...
    rainier-ui-icons ... Skipped
==> Extracting sources...
  -> Creating working copy of rainier-ui-icons git repo...
Reset branch 'makepkg'
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Entering fakeroot environment...
==> Starting package()...
cp: cannot stat 'Rainier': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...

**Comment by mali917** [comment]
Please help how to install this git in archlinux

**Comment by mali917** [comment]
admin1@ubuntu:~$ sudo add-apt-repository ppa:trenta.io/os
[sudo] password for admin1: 
 
 More info: https://launchpad.net/~trenta.io/+archive/ubuntu/os
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Hit:1 http://download.opensuse.org/repositories/home:/IBBoard:/cawbird/xUbuntu_19.10  InRelease
Ign:2 http://ppa.launchpad.net/trenta.io/os/ubuntu eoan InRelease              
Hit:3 http://security.ubuntu.com/ubuntu eoan-security InRelease                
Hit:4 http://us.archive.ubuntu.com/ubuntu eoan InRelease                       
Hit:5 http://ppa.launchpad.net/yannubuntu/boot-repair/ubuntu eoan InRelease
Hit:6 http://us.archive.ubuntu.com/ubuntu eoan-updates InRelease         
Err:7 http://ppa.launchpad.net/trenta.io/os/ubuntu eoan Release          
  404  Not Found [IP: 91.189.95.83 80]
Hit:8 http://us.archive.ubuntu.com/ubuntu eoan-backports InRelease
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/trenta.io/os/ubuntu eoan Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
admin1@ubuntu:~$ sudo apt update
Ign:1 http://ppa.launchpad.net/trenta.io/os/ubuntu eoan InRelease
Hit:2 http://security.ubuntu.com/ubuntu eoan-security InRelease                
Hit:3 http://download.opensuse.org/repositories/home:/IBBoard:/cawbird/xUbuntu_19.10  InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu eoan InRelease                       
Hit:5 http://ppa.launchpad.net/yannubuntu/boot-repair/ubuntu eoan InRelease
Hit:6 http://us.archive.ubuntu.com/ubuntu eoan-updates InRelease
Hit:7 http://us.archive.ubuntu.com/ubuntu eoan-backports InRelease       
Err:8 http://ppa.launchpad.net/trenta.io/os/ubuntu eoan Release          
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/trenta.io/os/ubuntu eoan Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
admin1@ubuntu:~$ sudo apt install trenta-icons
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package trenta-icons
admin1@ubuntu:~$ sudo add-apt-repository ppa:trenta.io/os
 
 More info: https://launchpad.net/~trenta.io/+archive/ubuntu/os
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Hit:1 http://download.opensuse.org/repositories/home:/IBBoard:/cawbird/xUbuntu_19.10  InRelease
Ign:2 http://ppa.launchpad.net/trenta.io/os/ubuntu eoan InRelease              
Hit:3 http://security.ubuntu.com/ubuntu eoan-security InRelease                
Hit:4 http://us.archive.ubuntu.com/ubuntu eoan InRelease                       
Hit:5 http://ppa.launchpad.net/yannubuntu/boot-repair/ubuntu eoan InRelease
Hit:6 http://us.archive.ubuntu.com/ubuntu eoan-updates InRelease         
Err:7 http://ppa.launchpad.net/trenta.io/os/ubuntu eoan Release          
  404  Not Found [IP: 91.189.95.83 80]
Hit:8 http://us.archive.ubuntu.com/ubuntu eoan-backports InRelease
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/trenta.io/os/ubuntu eoan Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
admin1@ubuntu:~$ sudo apt install trenta-icons
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package trenta-icons
admin1@ubuntu:~$

**Comment by KevDoy** [comment]
Thanks for letting us know. 
Have you tried this source?
https://aur.archlinux.org/packages/rainier-ui-icons-git

**Comment by KennyStier61** [comment]
The AUR package was not working because of the icon rebranding. You can now install them on Arch from the AUR. The package name is trenta-icons.

The PPA isn't working for you because we didn't have our icon theme uploaded for Ubuntu 19.10 (eoan) in `ppa:trenta.io/os`. I have uploaded sources for eoan so the PPA should work for you now.
