### ISSUE TITLE
Update AUR package

### ISSUE THREAD

**Issue by D3S0X** [trenta-io/trenta-icons#72]
The AUR package fails to build. It needs an update because of the new name

> ==> Making package: rainier-ui-icons-git 0.r446.9460016-1 (Sun 08 Mar 2020 10:00:45 PM CET)
> cp: cannot stat 'Rainier': No such file or directory
> ==> ERROR: A failure occurred in package().
>     Aborting...
> Error making: rainier-ui-icons-git

**Comment by KennyStier61** [comment]
I haven't used Arch for a few months now, but I'll try to fix the issue here soon

**Comment by KennyStier61** [comment]
Closed as duplicate of #70
