### ISSUE TITLE
Can you continue development

### ISSUE THREAD

**Issue by inLnx** [trenta-io/trenta-icons#82]
Why did you stop? You had something good going. You were on medium. I want to help you continue development based on Ubuntu 23.10. Trenta was going to end my distro hopping habit, but you discontinued it and none of the image files worked

**Comment by KevDoy** [comment]
We've moved on to other projects. 
That being said, I appreciate the kind words.

If you are looking to maintain Trenta OS going forward, please reach out to us at contact@trenta.io with your background, skills, and your cohesive plan for building and maintenance. Please include examples of projects you have maintained that has a similar scope and scale. 

Thank you.
